trigger:
    branches:
      include:
        - vm_ansible_modules

variables:
    vmImageName: 'ubuntu-latest'
    vmImageNameWindows: 'windows-latest'
    azureSubscription: 'Visual Studio Professional Subscription(e0fbe937-057c-4d67-9798-ab6191b88603)'

stages:
    - stage: Deploy
      displayName: 'Deploy complete infra with Ansible'
      jobs:
        - job: Deploy
          displayName: 'Deploy complete infra with Ansible'
          pool:
            vmImage: $(vmImageName)
          steps:
            - task: replacetokens@3
              inputs:
                targetFiles: '**/complete_infra.yml'
                encoding: 'auto'
                writeBOM: true
                actionOnMissing: 'warn'
                keepToken: false
                tokenPrefix: '__'
                tokenSuffix: '__'
            - task: Ansible@0
              inputs:
                ansibleInterface: 'agentMachine'
                playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/complete_infra.yml'
                inventoriesAgentMachine: 'file'
                inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/inventory.ini'
                args: '-vv'