trigger:
  - '*'

variables:
    vmImageName: 'ubuntu-latest'
    vmImageNameWindows: 'windows-latest'
    azureSubscription: 'Azure subscription 1(dd95eff5-7a32-4614-94e9-fde0c716cf96)'

stages:
    - stage: Create
      displayName: 'Build Infraestructure with Ansible'
      jobs:
        - job: Build
          displayName: 'Build Infraestructure Ansible'
          pool:
            vmImage: $(vmImageName)
          steps:
            - task: replacetokens@3
              displayName: 'Replace Tokens'
              inputs:
                targetFiles: '**/complete_infra.yml'
                encoding: 'auto'
                writeBOM: true
                actionOnMissing: 'warn'
                keepToken: false
                tokenPrefix: '__'
                tokenSuffix: '__'
            - task: Ansible@0
              displayName: 'Ansible Configuration - Modules'
              inputs:
                ansibleInterface: 'agentMachine'
                playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/complete_infra.yml'
                inventoriesAgentMachine: 'file'
                inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/inventory.ini'
                args: '-vv'
                failOnStdErr: false
    - stage: Copy
      condition: succeededOrFailed()
      displayName: 'Copy data to blob storage'
      jobs:
        - job: Copy
          displayName: 'Copy code to blob'
          pool:
            vmImage: $(vmImageNameWindows)
          steps:
            - task: AzureFileCopy@3
              displayName: 'Copy zip to Blob'
              inputs:
                SourcePath: '$(System.DefaultWorkingDirectory)/crud-app/crud.zip'
                azureSubscription: 'Azure subscription 1(dd95eff5-7a32-4614-94e9-fde0c716cf96)'
                Destination: 'AzureBlob'
                storage: '$(storageAccountName)'
                ContainerName: '$(containerName)'
            - task: AzureFileCopy@3
              displayName: 'Copy script to Blob'
              inputs:
                SourcePath: '$(System.DefaultWorkingDirectory)/crud-app/script.sh'
                azureSubscription: 'Azure subscription 1(dd95eff5-7a32-4614-94e9-fde0c716cf96)'
                Destination: 'AzureBlob'
                storage: '$(storageAccountName)'
                ContainerName: '$(containerName)'
      
    - stage: Config_Web_Server
      condition: succeededOrFailed()
      displayName: 'Config Web Server'
      jobs:
      - job: Config
        displayName: 'Config Web Server'
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: replacetokens@3
            displayName: 'Replace Tokens in playbook'
            inputs:
              targetFiles: '**/config_vm_ws.yml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '__'
              tokenSuffix: '__'
          - task: replacetokens@3
            displayName: 'Replace Tokens in inventory'
            inputs:
              targetFiles: '**/hosts-modules'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '__'
              tokenSuffix: '__'

          - task: Ansible@0
            displayName: 'Install Apache with wsgi'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/config_vm_ws.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/hosts-modules'
              args: '-vvv'
              failOnStdErr: false
                
    - stage: Config_DB
      condition: succeededOrFailed()
      displayName: 'Config Database'
      jobs:  
      - job: Config
        displayName: 'Config Database'
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: replacetokens@3
            displayName: 'Replace Tokens in playbook'
            inputs:
              targetFiles: '**/config_vm_db.yml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '__'
              tokenSuffix: '__'
          
          - task: replacetokens@3
            displayName: 'Replace Tokens in inventory'
            inputs:
              targetFiles: '**/hosts-modules'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '__'
              tokenSuffix: '__'

          - task: Ansible@0
            displayName: 'Install mysql db'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/config_vm_db.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/hosts-modules'
              args: '-vvv'
              failOnStdErr: false

    - stage: Deploy
      condition: succeededOrFailed()
      displayName: 'Deploy Application'
      jobs:  
      - job: Test
        displayName: 'Deploy Application'
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: replacetokens@3
            displayName: 'Replace Tokens in playbook'
            inputs:
              targetFiles: '**/config_vm_extension.yml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '__'
              tokenSuffix: '__'

          - task: Ansible@0
            displayName: 'Deploy with Ansible'
            inputs:
              ansibleInterface: 'agentMachine'
              playbookPathOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/config_vm_extension.yml'
              inventoriesAgentMachine: 'file'
              inventoryFileOnAgentMachine: '$(System.DefaultWorkingDirectory)/playbooks/inventory.ini'
              args: '-vvv'
              failOnStdErr: false