---
    -   name: "Create VM Extension"
        azure_rm_virtualmachineextension:
            name: myvmextension
            location: "{{location}}"
            resource_group: "{{resource_group_name}}"
            virtual_machine_name: "{{ vm_name }}"
            publisher: Microsoft.Azure.Extensions
            virtual_machine_extension_type: CustomScript
            type_handler_version: 2.0
            settings: "{{ settings }}"
            auto_upgrade_minor_version: true