---
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
      become: yes
    
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      become: yes
      notify: restart apache2