---
- include_role:
    name: create-resources

    # - name: "Create {{availabilityset_name}} Availability Set"
    #   azure_rm_availabilityset:
    #     name: "{{availabilityset_name}}"
    #     location: "{{location}}"
    #     resource_group: "{{resourcegroup_name}}"
    #     sku: Aligned

- name: "Create VM {{ vm_name }} with predefined Infra"
  shell: "az vm create -g {{ resource_group_name }} -n {{ vm_name }} --image UbuntuLTS --admin-username {{ vm_user }} --admin-password {{ vm_pwd }} --nic {{ network_interface_name }} --storage-account {{ storage_account_name }} --storage-container-name {{ storage_container_name }} --size {{ vm_size }} --use-unmanaged-disk"