-   hosts: localhost
    gather_facts: false

    vars:
        az_pwd: "JORlaresp1970!"
        az_user: "jorge.lara@globant.com"

    tasks:
        -   name: Login to Azure
            shell: "az login -u {{ az_user }} -p {{ az_pwd }}"
  