- hosts: localhost
  gather_facts: false
  
  vars:
    az_pwd: __azPass__
    az_user: __azUser__
    storage_account_name: __storageAccountName__
    storage_container_name: __containerName__
    
  tasks:
    - name: Login to Azure
      shell: "az login -u {{ az_user }} -p {{ az_pwd }}"

    - name: copy crud to web machine
      include_role:
        name: vm-extension
      vars:
        settings: '{"fileUris": ["https://mystorageaccountdavor.blob.core.windows.net/mycontainernamedavor/crud.zip"],"commandToExecute": "cp crud.zip /tmp"}'
        #settings: '{"fileUris": ["https://{{storage_account_name}}.blob.core.windows.net/{{storage_container_name}}/crud.zip"],"commandToExecute": "cp crud.zip /tmp"}'
        vm_name: __vmName__
        resource_group_name: __resourceGroupName__

    - name: copy crud to db machine
      include_role:
        name: vm-extension
      vars:
        settings: '{"fileUris": ["https://mystorageaccountdavor.blob.core.windows.net/mycontainernamedavor/crud.zip"],"commandToExecute": "cp crud.zip /tmp"}'
        #settings: '{"fileUris": ["https://{{storage_account_name}}.blob.core.windows.net/{{storage_container_name}}/crud.zip"],"commandToExecute": "cp crud.zip /tmp"}'
        vm_name: __vmName__-db
        resource_group_name: __resourceGroupName__

    - name: copy sql file - db machine
      include_role:
        name: vm-extension
      vars:
        settings: '{"fileUris": ["https://mystorageaccountdavor.blob.core.windows.net/mycontainernamedavor/mysqld.cnf"],"commandToExecute": "cp mysqld.cnf /tmp"}'
        #settings: '{"fileUris": ["https://{{storage_account_name}}.blob.core.windows.net/{{storage_container_name}}/crud.zip"],"commandToExecute": "cp crud.zip /tmp"}'
        vm_name: __vmName__-db
        resource_group_name: __resourceGroupName__

    - name: install crud - web machine
      include_role:
        name: vm-extension
      vars:
        settings: '{"fileUris": ["https://mystorageaccountdavor.blob.core.windows.net/mycontainernamedavor/script.sh"],"commandToExecute": "cp script.sh /tmp && cd /tmp && touch output.log && bash ./script.sh >> output.log"}'
        #settings: '{"fileUris": ["https://{{storage_account_name}}.blob.core.windows.net/{{storage_container_name}}/script.sh"],"commandToExecute": "cp script.sh /tmp && cp mysqld.cnf /tmp && cd /tmp && sudo mv mysqld.cnf /etc/mysql/mysql.conf.d/ && touch output.log && bash ./script.sh >> output.log"}'
        vm_name: __vmName__
        resource_group_name: __resourceGroupName__

    - name: install crud - db machine
      include_role:
        name: vm-extension
      vars:
        settings: '{"fileUris": ["https://mystorageaccountdavor.blob.core.windows.net/mycontainernamedavor/script.sh"],"commandToExecute": "cp script.sh /tmp && cd /tmp && touch output.log && bash ./script.sh >> output.log"}'
        #settings: '{"fileUris": ["https://{{storage_account_name}}.blob.core.windows.net/{{storage_container_name}}/script.sh"],"commandToExecute": "cp script.sh /tmp && cp mysqld.cnf /tmp && cd /tmp && sudo mv mysqld.cnf /etc/mysql/mysql.conf.d/ && touch output.log && bash ./script.sh >> output.log"}'
        vm_name: __vmName__-db
        resource_group_name: __resourceGroupName__